version: '2'
services:
  nginx-proxy:
    build: ./
    image: rnds/nginx-hiver
    container_name: nginx-hiver
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local